name: Scala Steward

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest

    steps:
    - uses: scala-steward-org/scala-steward-action@v2
      with:
        github-token: ${{ secrets.TOKEN }}
        author-email: matankdr@gmail.com
        author-name: matankdr
